########################
##### EXPERIMENTAL #####
########################

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME PRE-BUILT                                                                         #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  device_name: nspanel
  wifi_ssid: nspanel
  wifi_password: NSPanel_Blueprint

packages:
  core_package: !include ../esphome/nspanel_esphome_core.yaml
  standard_package: !include ../esphome/nspanel_esphome_standard.yaml
  ota_http: !include ../esphome/nspanel_esphome_addon_ota_http.yaml

captive_portal:
  id: ap_captive_portal

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/prebuilt/nspanel_esphome_prebuilt.yaml@main
  import_full_config: false

esp32:  ##### REMOVE THIS AFTER ESPHome v2024.12.0 IS RELEASED
  framework:
    type: esp-idf
    version: 5.1.5
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.5/esp-idf-v5.1.5.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip

esp32_ble:
  id: ble

esp32_improv:
  id: ble_improv
  authorizer: none

esp32_ble_server:
  id: ble_server

esphome:
  name_add_mac_suffix: true
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_PREBUILT

improv_serial:
  id: serial_improv

logger:
  baud_rate: 115200

ota:
  - id: !extend ota_std
    password: !remove

script:
  - id: !extend dump_config_packages  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          ESP_LOGCONFIG("${project_tag}", "  - Pre-built");

wifi:
  networks: !remove
  ap: {}
  power_save_mode: LIGHT  # To make it compatible with BLE
...
