---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  advanced_package: !include ../esphome/nspanel_esphome_advanced.yaml

esp32:
  framework:
    type: esp-idf
    version: 5.1.5
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.5/esp-idf-v5.1.5.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
...
