#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Blank                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_SETTINGS: '1UL << 28'
  PAGE_ID_SETTINGS: '8'

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (page_id == 8) {  // Page Settings
              switch (component_id) {
                case 9:  // Reboot button
                  if (!touch_event) {  // Release
                    ESP_LOGW("display.on_touch", "Restarting ESPHome");
                    arch_restart();
                  }
                  break;
              }
            }

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_PAGE_SETTINGS

number:
  - id: !extend display_brightness
    on_value:
      then:
        - lambda: |-
            disp1->set_component_value("settings.brightslider", int(x));
            if (current_page_id == ${PAGE_ID_SETTINGS})
              disp1->set_component_text_printf("bright_text", "%i%%", int(x));

  - id: !extend display_dim_brightness
    on_value:
      then:
        - lambda: |-
            disp1->set_component_value("settings.dimslider", int(x));
            if (current_page_id == ${PAGE_ID_SETTINGS})
              disp1->set_component_text_printf("dim_text", "%i%%", int(x));

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_SETTINGS}, "Page Settings");

  - id: !extend set_var_bool
    then:
      - lambda: |-
          if (component == "BOOT_STEP_PAGE_SETTINGS")
            boot_progress->execute(${BOOT_STEP_PAGE_SETTINGS}, "Page Settings");

  - id: !extend set_var_string
    then:
      - lambda: |-
          if (component == "lbl_bright")
            display_wrapped_text->execute(${PAGE_ID_SETTINGS}, "lbl_bright", val.c_str(),
                                          id(display_mode) == 2 ? 25 : 10);
          else if (component == "lbl_dim")
            display_wrapped_text->execute(${PAGE_ID_SETTINGS}, "lbl_dim", val.c_str(),
                                          id(display_mode) == 2 ? 25 : 10);
...
