#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - ALARM PAGE                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
###############################

---
substitutions:
  BOOT_STEP_PAGE_UTILITIES: '1UL << 24'
  PAGE_ID_UTILITIES: '27'

api:
  id: !extend api_server
  actions:
    # Utilities group refresh
    - action: utilities_group_refresh
      variables:
        group_id: string
        value1: string
        value2: string
        direction: int
        constructor: bool
      then:
        - lambda: |-
            if (!group_id.empty()) {
              uint8_t id = findUtilitiesGroupIndex(group_id.c_str());
              if (id != UINT8_MAX) {
                // Update Value 1
                if (!value1.empty() and
                    (constructor or strcmp(value1.c_str(), UtilitiesGroups[id].value1) != 0)) {
                  copyStringToCharArray(UtilitiesGroups[id].value1, value1);
                  disp1->set_component_text(group_id.c_str(), value1.c_str());
                }

                // Update Value 2
                if (!value2.empty() and
                    (constructor or strcmp(value2.c_str(), UtilitiesGroups[id].value2) != 0)) {
                  copyStringToCharArray(UtilitiesGroups[id].value2, value2);
                  disp1->set_component_text((group_id + "b").c_str(), value2.c_str());
                }

                // Update direction
                if (group_id != "grid" and !isnan(direction) and
                    (constructor or direction != UtilitiesGroups[id].direction)) {
                  UtilitiesGroups[id].direction = direction;
                  disp1->set_component_value((group_id + "_line_d").c_str(), direction);
                }
              }
            }

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_UTILITIES}, "Page Utilities");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          boot_progress->execute(${BOOT_STEP_PAGE_UTILITIES}, "Page Utilities");

  - id: !extend page_changed
    then:
      - lambda: |-
          if (id(current_page_id) == ${PAGE_ID_UTILITIES})
            page_utilities->execute();

  - id: !extend page_home
    then:
      - script.execute: page_home_bt_utilities

  - id: page_home_bt_utilities
    mode: restart
    then:
      - lambda: |-
          static DisplayComponent* bt_utilities = get_component(${PAGE_ID_HOME}, "bt_utilities");
          if (bt_utilities->initialized) {
            ESP_LOGD("script.page_home_bt_utilities", "Updating bt_utilities");
            display_component_send->execute(bt_utilities);
          }

  - id: page_utilities
    mode: restart
    then:
      - lambda: |-
          if (UtilitiesGroups == nullptr)
            resetUtilitiesGroups();

  - id: !extend stop_all
    then:
      - lambda: |-
          cleanupUtilitiesGroups();
          page_home_bt_utilities->stop();
          page_utilities->stop();
...
