#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page keyb_num                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_KEYBOARD_NUM: '1UL << 18'
  PAGE_ID_KEYB_NUM: '24'

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_PAGE_KEYB_NUM

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_KEYBOARD_NUM}, "Page Keyboard (Num)");

  - id: !extend event_from_display
    then:
      - lambda: |-
          if (page == "keyb_num") {
            const std::string base_domain = json["base_domain"];
            if (base_domain == "alarm") {
              const std::string key = json["key"];
              const std::string code_format = json["code_format"];
              const std::string pin = json["pin"];
              alarm_control_panel_action->execute(detailed_entity->state.c_str(), key.c_str(),
                                                  code_format.c_str(), pin.c_str());
            }
            goto_page_id->execute(get_page_id(base_domain.empty() ? "home" : base_domain.c_str()), false);
          }

  - id: !extend set_var_bool
    then:
      - lambda: |-
          if (component == "BOOT_STEP_PAGE_KEYBOARD_NUM")
            boot_progress->execute(${BOOT_STEP_PAGE_KEYBOARD_NUM}, "Page Keyboard (Num)");
...
