#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE                                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE

packages:
  # yamllint disable rule:colons
  versioning:       !include nspanel_esphome_core_versioning.yaml
  api:              !include nspanel_esphome_core_api.yaml
  base:             !include nspanel_esphome_core_base.yaml
  boot:             !include nspanel_esphome_core_boot.yaml
  datetime:         !include nspanel_esphome_core_datetime.yaml
  hw_buttons:       !include nspanel_esphome_core_hw_buttons.yaml
  hw_display:       !include nspanel_esphome_core_hw_display.yaml
  hw_memory:        !include nspanel_esphome_core_hw_memory.yaml
  hw_wifi:          !include nspanel_esphome_core_hw_wifi.yaml
  page_boot:        !include nspanel_esphome_core_page_boot.yaml
  page_home:        !include nspanel_esphome_core_page_home.yaml
  page_screensaver: !include nspanel_esphome_core_page_screensaver.yaml
  # yamllint enable rule:colons
...
