#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - QRCODE                                                                     #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_QRCODE: '1UL << 22'
  PAGE_ID_QRCODE: '17'
  qrcode_size: '200'
  qrcode_background_color: '65535'
  qrcode_foreground_color: '0'
  qrcode_logo_pic: '-1'
  qrcode_border_width: '8'

api:
  id: !extend api_server
  actions:
    # Dynamically displays QR codes on the ESPHome UI for sharing information such as WiFi passwords or website links.
    - action: qrcode
      variables:
        title: string   # Heading or title for the QR code, offering context or instructions.
        qrcode: string  # Data or URL to be encoded into the QR code.
        show: bool      # Flag to immediately display the QR code page upon action invocation.
      then:
        - lambda: |-
            id(qrcode_string) = qrcode;
            display_component_update_text->execute(get_component(${PAGE_ID_QRCODE}, "qrcode_label"), title.c_str());
            if (show)
              goto_page_id->execute(${PAGE_ID_QRCODE}, true);
            if (!complete_boot_step(${BOOT_STEP_PAGE_QRCODE}))
              boot_progress->execute(${BOOT_STEP_PAGE_QRCODE}, "Page QRcode");

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_PAGE_QRCODE

globals:
  - id: qrcode_string
    type: std::string
    restore_value: false
    max_restore_data_length: 100
    initial_value: '""'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_QRCODE}, "Page QRcode");

  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page_id == ${PAGE_ID_QRCODE})
            page_qrcode->execute();

  # Load the QRCode page
  - id: page_qrcode
    mode: restart
    then:
      - lambda: |-
          if (!id(qrcode_string).empty())
            disp1->qrcode(((id(display_mode) == 2 ? 320 : 480)-200)/2,  // x1
                          ((id(display_mode) == 2 ? 480 : 320)-200)/2,  // y1
                          id(qrcode_string).c_str(),                    // content
                          ${qrcode_size},                               // size
                          ${qrcode_background_color},                   // background_color
                          ${qrcode_foreground_color},                   // foreground_color
                          ${qrcode_logo_pic},                           // logo pic id
                          ${qrcode_border_width}                        // border_width
                        );

  - id: !extend stop_all
    then:
      - lambda: |-
          page_qrcode->stop();
...
