#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Weather                                                               #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_WEATHER: '1UL << 25'
  PAGE_ID_WEATHER01: '2'
  PAGE_ID_WEATHER02: '3'
  PAGE_ID_WEATHER03: '4'
  PAGE_ID_WEATHER04: '5'
  PAGE_ID_WEATHER05: '6'

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if  (
                  page_id == ${PAGE_ID_HOME}  // Page Home
                  and id(weather_pic) > 1  // Some weather pic is shown
                  and api_server->is_connected()
                  and
                    (
                      component_id == 5     // outdoor temperature
                      or component_id == 7  // weather
                    )
                ) {
              goto_page_id->execute(${PAGE_ID_WEATHER01}, false);
            }

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_PAGE_WEATHER

globals:
  - id: weather_pic
    type: uint8_t
    restore_value: false
    initial_value: '1'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_WEATHER}, "Page Weather");

  - id: !extend page_home
    then:
      - lambda: |-
          set_component_pic->execute(${PAGE_ID_HOME}, "weather", id(weather_pic));

  - id: !extend set_var_number
    then:
      - lambda: |-
          if (component == "weather_pic" and val>=1 and val<=15) {
            if (id(weather_pic) != val) {
              id(weather_pic) = static_cast<uint8_t>(val);
              if (current_page_id == ${PAGE_ID_HOME})
                set_component_pic->execute(${PAGE_ID_HOME}, "weather", val);
            }
            boot_progress->execute(${BOOT_STEP_PAGE_WEATHER}, "Page Weather");
          }
...
