#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - ALARM PAGE                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
###############################

---
substitutions:
  BOOT_STEP_PAGE_CLIMATE: '1UL << 12'
  PAGE_ID_CLIMATE: '7'

api:
  id: !extend api_server
  actions:
    # Dynamically updates the climate page with the latest climate control settings and status.
    - action: page_climate
      variables:
        current_temp: float      # Current temperature reading.
        supported_features: int  # Bitmask indicating the supported features of the climate device, such as temperature control (1) and fan mode (4).
        target_temp: float       # Desired target temperature setting.
        target_temp_high: float  # Upper limit of the target temperature range for devices supporting ranges.
        target_temp_low: float   # Lower limit of the target temperature range.
        temp_step: int           # Temperature adjustment step size, indicating the granularity of changes (multiplied by 10 for precision).
        total_steps: int         # Total adjustment steps available, derived from the device's temperature range and step size.
        temp_offset: int         # Calibration offset applied to the temperature reading (multiplied by 10 for precision).
        climate_icon: string     # Icon codepoint representing the current climate status, chosen from HASwitchPlate Material Design Icons.
        embedded_climate: bool   # Indicates if climate control is integrated into the interface.
        entity: string           # Entity ID of the climate device, allowing for direct control and status updates.
      then:
        - script.stop: set_climate
        - if:
            condition:
              - text_sensor.state:
                  id: current_page
                  state: climate
            then:
              - text_sensor.template.publish:
                  id: detailed_entity
                  state: !lambda return entity;
        - script.execute:
            id: set_climate
            current_temp: !lambda return current_temp;
            supported_features: !lambda return supported_features;
            target_temp: !lambda return target_temp;
            target_temp_high: !lambda return target_temp_high;
            target_temp_low: !lambda return target_temp_low;
            temp_step: !lambda return temp_step;
            total_steps: !lambda return total_steps;
            temp_offset: !lambda return temp_offset;
            climate_icon: !lambda return climate_icon;
            embedded_climate: !lambda return embedded_climate;

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (
                  page_id == ${PAGE_ID_HOME}
                  and id(is_climate)
                  and (
                    component_id == 4      // indr_temp
                    or component_id == 27  // indr_temp_icon
                  )
                ) {
              goto_page_id->execute(${PAGE_ID_CLIMATE}, false);
            }

globals:
  - id: is_climate
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: mui_unavailable
    type: std::string
    restore_value: true
    initial_value: '"Unavailable"'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_CLIMATE}, "Page Climate");

  - id: change_climate_state
    mode: restart
    parameters:
      embedded: bool
      key: string
      value: string
    then:
      - lambda: |-
          if (not embedded) {
            if (key == "temperature" or key == "target_temp_high" or key == "target_temp_low")
              ha_call_action->execute("climate.set_temperature", key.c_str(), to_string(stof(value) / 10), detailed_entity->state.c_str());
            else if (key == "hvac_mode")
              ha_call_action->execute("climate.set_hvac_mode", key.c_str(), value.c_str(), detailed_entity->state.c_str());
          }

  - id: !extend event_from_display  # Defined by nspanel_esphome_core_hw_display.yaml
    then:
      - if:
          condition:
            - lambda: return page == "climate";
          then:
            - lambda: |-
                const std::string key = json["key"];
                const uint8_t embedded = json["embedded"];
                const std::string value = json["value"];
                change_climate_state->execute(embedded == 1, key.c_str(), value.c_str());

  - id: page_climate
    mode: restart
    then:  # There's nothing here so far

  - id: !extend page_changed
    then:
      - if:
          condition:
            - text_sensor.state:
                id: current_page
                state: climate
          then:
            - script.execute: page_climate

  - id: set_climate
    mode: restart
    parameters:
      current_temp: float
      supported_features: int
      target_temp: float
      target_temp_high: float
      target_temp_low: float
      temp_step: uint
      total_steps: uint
      temp_offset: int
      climate_icon: string
      embedded_climate: bool
    then:
      - lambda: |-
          if (id(current_page_id) == ${PAGE_ID_CLIMATE}) {
            bool useDecimal = (temp_step % 10 != 0);
            char buffer[15];
            disp1->send_command_printf("climateslider.maxval=%i", total_steps);
            disp1->send_command_printf("slider_high.maxval=%i", total_steps);
            disp1->send_command_printf("slider_low.maxval=%i", total_steps);
            set_component_value->execute("climate", "temp_offset", temp_offset);
            set_component_value->execute("climate", "temp_step", temp_step);
            char dec_separator_str[2] = {id(mui_decimal_separator), '\0'};
            set_component_text->execute("climate", "dec_separator", dec_separator_str);
            set_component_visibility->execute("climate", "current_temp", true);
            if (current_temp > -999) {
              snprintf(buffer, sizeof(buffer), (useDecimal) ? "%.1f°" : "%.0f°", current_temp);
              set_component_text->execute("climate", "current_temp", adjustDecimalSeparator(buffer, id(mui_decimal_separator)).c_str());
            }
            else
              set_component_text->execute("climate", "current_temp", id(mui_unavailable).c_str());

            if (target_temp > -999) {  // Target temp enabled
              set_component_value->execute("climate", "active_slider", 0);
              snprintf(buffer, sizeof(buffer), (useDecimal) ? "%.1f°" : "%.0f°", target_temp);
              set_component_text->execute("climate", "target_high", adjustDecimalSeparator(buffer, id(mui_decimal_separator)).c_str());
              set_component_value->execute("climate", "climateslider", round(((10*target_temp) - temp_offset) / temp_step));
              set_component_visibility->execute("climate", "slider_high", false);
              set_component_visibility->execute("climate", "slider_low", false);
              set_component_visibility->execute("climate", "target_low", false);
              set_component_visibility->execute("climate", "target_high", true);
              set_component_visibility->execute("climate", "climateslider", true);
            } else {
              set_component_visibility->execute("climate", "slider_high", false);
              if (target_temp_low > -999) {  // Target temp low enabled
                set_component_value->execute("climate", "active_slider", 2);
                snprintf(buffer, sizeof(buffer), (useDecimal) ? "%.1f°" : "%.0f°", target_temp_low);
                set_component_text->execute("climate", "target_low", adjustDecimalSeparator(buffer, id(mui_decimal_separator)).c_str());
                set_component_value->execute("climate", "slider_low", round(((10*target_temp_low) - temp_offset) / temp_step));
                set_component_visibility->execute("climate", "target_low", true);
                set_component_visibility->execute("climate", "slider_low", true);
              } else {
                set_component_visibility->execute("climate", "target_low", false);
                set_component_visibility->execute("climate", "slider_low", false);
              }
              if (target_temp_high > -999) {  // Target temp high enabled
                set_component_value->execute("climate", "active_slider", 1);
                snprintf(buffer, sizeof(buffer), (useDecimal) ? "%.1f°" : "%.0f°", target_temp_high);
                set_component_text->execute("climate", "target_high", adjustDecimalSeparator(buffer, id(mui_decimal_separator)).c_str());
                set_component_value->execute("climate", "slider_high", round(((10*target_temp_high) - temp_offset) / temp_step));
                set_component_visibility->execute("climate", "target_high", true);
                set_component_visibility->execute("climate", "slider_high", true);
              } else {
                set_component_visibility->execute("climate", "target_high", false);
                set_component_visibility->execute("climate", "slider_high", false);
              }
            }
            if (target_temp > -999 or target_temp_high > -999 or target_temp_low > -999) {
              set_component_text->execute("climate", "target_icon", climate_icon.c_str());
              set_component_visibility->execute("climate", "target_icon", true);
              set_component_visibility->execute("climate", "decrease_temp", true);
              set_component_visibility->execute("climate", "increase_temp", true);
            } else {
              set_component_visibility->execute("climate", "target_icon", false);
              set_component_visibility->execute("climate", "decrease_temp", false);
              set_component_visibility->execute("climate", "increase_temp", false);
            }
            set_component_value->execute("climate", "embedded", (embedded_climate) ? 1 : 0);
          }

  - id: !extend set_var_string
    then:
      - lambda: |-
          if (component == "mui_unavailable") {
            id(mui_unavailable) = val;
            boot_progress->execute(${BOOT_STEP_PAGE_CLIMATE}, "Page Climate");
          }

  - id: !extend stop_all
    then:
      - script.stop: change_climate_state
      - script.stop: page_climate
      - script.stop: set_climate

  - id: !extend set_var_bool
    then:
      - lambda: |-
          if (component == "is_climate")
            id(is_climate) = val;

...
