#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Entities                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_ENTITIES: '1UL << 15'
  PAGE_ID_ENTITYPAGE01: '18'
  PAGE_ID_ENTITYPAGE02: '19'
  PAGE_ID_ENTITYPAGE03: '20'
  PAGE_ID_ENTITYPAGE04: '21'
  half_width_chars: "iljtIf '-,;:!.\\\"|()[]{}*^~\\\\/_"

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_PAGE_ENTITIES

globals:
  - id: page_entity_value_horizontal_alignment
    type: uint8_t
    restore_value: false
    initial_value: '1'  # Horizontal alignment:0-Left;1-Center;2-Right

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_ENTITIES}, "Page Entities");

  - id: !extend page_changed
    then:
      - lambda: |-
          if (is_page_in_group(ENTITY_PAGE_MASK)) page_entitypage->execute();

  - id: page_entitypage
    mode: restart
    then:
      - lambda: |-
          if (id(page_entity_value_horizontal_alignment) != 1)
            page_entitypage_aligh_values->execute();

  - id: page_entitypage_aligh_values
    mode: restart
    then:
      - if:
          condition:
            - lambda: |-
                return is_page_in_group(ENTITY_PAGE_MASK);
          then:
            - repeat:
                count: 8
                then:
                  - delay: !lambda return display_delay->state;
                  - lambda: |-
                      disp1->send_command_printf("value%02" PRIu32 ".xcen=%" PRIu8, iteration,
                                                id(page_entity_value_horizontal_alignment));

  - id: !extend set_component_text
    then:
      - lambda: |-
          if (!text.empty() and current_page_id == page_id and is_page_in_group(ENTITY_PAGE_MASK)) {
            // Adjusted length starts at 0
            float adjusted_length = 0.0;

            // Iterate over each character in the string
            for (char const &c: text) {
              // Check if character is a space or other specified exceptions
              if (id(display_charset)== ${DISPLAY_CHARSET_CJK} or
                  std::string("${half_width_chars}").find(c) != std::string::npos) {
                adjusted_length += 0.5; // Count these as half
              } else {
                adjusted_length += 1.0; // Count all other characters as 1
              }
            }
            // Decide which font to use based on adjusted length
            if (adjusted_length > 8.0)
              display_component_update_font->execute(get_component(page_id, component.c_str()),
                                                      adjusted_length <= 12.0 ? 1 : 0);
          }

  - id: !extend set_var_number
    then:
      - lambda: |-
          if (component == "page_entity_value_horizontal_alignment") {
            if (id(page_entity_value_horizontal_alignment) != val and val >= 0 and val <= 2) {
              id(page_entity_value_horizontal_alignment) = static_cast<uint8_t>(val);
              page_entitypage_aligh_values->execute();
            }
            boot_progress->execute(${BOOT_STEP_PAGE_ENTITIES}, "Page Entities");
          }

  - id: !extend stop_all
    then:
      - lambda: |-
          page_entitypage->stop();
...
