#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - BOOT                                                                       #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_BOOT: '1UL << 1'

api:
  id: !extend api_service
  on_client_connected:
    then:
      - script.execute:
          id: boot_log
          category: API
          log_message: Client connected

display:
  - id: !extend disp1
    on_setup:
      then:
        - lambda: |-
            send_command->execute("esphome=0");
            set_brightness->execute(100);
            nextion_init->publish_state(disp1->is_setup());

    on_touch:
      then:
        - lambda: |-
            if (page_id == 0) {  // Boot
              switch (component_id) {
                case 24:  // Reboot button
                  if (!touch_event) {  // Release
                    arch_restart();
                  }
                  break;
              }
            }

esphome:
  on_boot:
    - priority: 600.0
      then:
        - script.execute: boot_sequence

script:
  - id: boot_event
    mode: restart
    then:
      - delay: 120s
      - while:
          condition:
            - lambda: return not is_boot_complete();
          then:
            - homeassistant.event:
                event: esphome.nspanel_ha_blueprint
                data:
                  device_name: !lambda return device_name->state.c_str();
                  esphome_version: ${version}
                  type: boot
                  step: timeout
                  completed_boot_steps: !lambda return completed_boot_steps;
            - delay: 120s

  - id: boot_progress
    mode: restart
    parameters:
      step: uint32_t
      step_name: string
    then:
      - lambda: |-
          boot_progress_dump_timer->execute();
          complete_boot_step(step);
          ESP_LOGI("script.boot_progress", "Boot step completed: %s (step %i of %i - %i%%)", step_name.c_str(),
                    get_boot_steps_completed(), TOTAL_BOOT_STEPS, get_boot_progress_percentage());
          if (is_boot_complete())
            ESP_LOGI("script.boot_progress", "Progress: Boot sequence completed");

  - id: boot_progress_dump
    mode: queued
    then:
      - lambda: |-
          ESP_LOGCONFIG("script.boot_progress_dump", "Boot progress: %" PRIu8 "%% (%" PRIu32 ")",
                        get_boot_progress_percentage(), completed_boot_steps);
          boot_progress_dump_item->execute(${BOOT_STEP_BOOT}, "Boot");

  - id: boot_progress_dump_item
    mode: queued
    parameters:
      step: uint32_t
      step_name: string
    then:
      - lambda: |-
          int8_t padding = std::max(0, 21 - static_cast<int>(step_name.length())); // Calculate dynamic padding
          ESP_LOGCONFIG("script.boot_progress_dump", " - %s:%*s%s", step_name.c_str(), padding, "",
                        is_boot_step_completed(step) ? "Completed" : "PENDING");

  - id: boot_progress_dump_timer
    mode: restart
    then:
      - wait_until:
          condition:
            - lambda: return get_boot_progress_percentage() == 100;
          timeout: 60s
      - script.execute: boot_progress_dump

  - id: boot_sequence
    mode: single
    then:
      - lambda: |-
          if (!disp1->is_setup())
            boot_log->execute("Boot", "Waiting for Nextion");
      - wait_until:
          condition:
            - lambda: return disp1->is_setup();
          timeout: 10s
      - delay: 1s
      - lambda: |-
          if (id(current_page_id) != ${PAGE_ID_BOOT}) {
            page_changed->execute(${PAGE_ID_BOOT});
            boot_log->execute("Boot", "Waiting for page Boot");
          }
      - wait_until:
          condition:
            - lambda: return id(current_page_id) == ${PAGE_ID_BOOT};
          timeout: 10s
      - lambda: |-
          if (!wifi_component->is_connected())
            boot_log->execute("Boot", "Waiting for Wi-Fi");
      - wait_until:
          condition:
            - wifi.connected:
          timeout: 10s
      - lambda: |-
          if (!api_server->is_connected())
            boot_log->execute("Boot", "Waiting for API");
      - wait_until:
          condition:
            - api.connected:
          timeout: 10s
      - delay: 2s
      - lambda: |-
          boot_log->execute("Boot", "Report to Blueprint");
      - homeassistant.event:
          event: esphome.nspanel_ha_blueprint
          data:
            device_name: !lambda return device_name->state.c_str();
            esphome_version: ${version}
            type: boot
            step: start
            completed_boot_steps: !lambda return completed_boot_steps;
      - lambda: |-
          boot_log->execute("Boot", "Display settings");
      - script.execute:
          id: set_variable_value
          variable: brightness_sleep
          val: !lambda return static_cast<uint8_t>(display_sleep_brightness->state);
      - lambda: |-
          set_variable_value->execute("brightness_dim", static_cast<uint8_t>(display_dim_brightness->state));
          set_variable_value->execute("brightness", static_cast<uint8_t>(display_brightness->state));
          set_component_value->execute("settings", "dimslider", static_cast<uint8_t>(display_dim_brightness->state));
          set_component_value->execute("settings", "brightslider", static_cast<uint8_t>(display_brightness->state));
          set_brightness->execute(display_brightness->state);
          boot_progress->execute(${BOOT_STEP_BOOT}, "Boot");
          boot_event->execute();

  - id: !extend dump_config
    then:
      - lambda: |-
          if (is_boot_complete())
            ESP_LOGCONFIG("${project_tag}", "Boot steps: %" PRIu8 "/%" PRIu8 " (100%%)",
                          get_boot_steps_completed(), TOTAL_BOOT_STEPS);
          else {
            ESP_LOGW("${project_tag}", "Boot steps: %" PRIu8 "/%" PRIu8 " (%" PRIu8 "%% - %" PRIu32 ")",
                      get_boot_steps_completed(), TOTAL_BOOT_STEPS,
                      get_boot_progress_percentage(), completed_boot_steps);
            ESP_LOGW("${project_tag}", "  State:    %s",
                      ((wifi_component->is_connected()) and api_server->is_connected()) ? "Pending" : "DISCONNECTED");
            boot_progress_dump->execute();
            ESP_LOGCONFIG("${project_tag}", "Requesting new boot parameters from Blueprint");
            boot_event->execute();
          }

  - id: !extend stop_all
    then:
      - lambda: |-
          boot_event->stop();
          boot_progress->stop();
          boot_progress_dump_timer->stop();
...
