name: Code scan

on:
  push:
    #paths:
      #- "*.yaml"
      #- "*.yml"
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Code scan
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Validate nspanel_blueprint.yaml
        run: yamllint -d relaxed nspanel_blueprint.yaml
      - name: Validate nspanel_esphome.yaml
        run: yamllint -d relaxed nspanel_esphome.yaml
