name: Code scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  code_scan:
    name: Code scan
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: nwisbeta/validate-yaml-schema@v1.0.3
