name: Code scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  code_scan:
    name: Code scan
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      #- uses: nwisbeta/validate-yaml-schema@v1.0.3
      - id: validate-yaml-schema
        uses: ./
        with:
          yamlSchemasJson: |
            {
              "https://json.schemastore.org/github-action.json": ["action.yml", "action.yaml"],
              "https://json.schemastore.org/github-workflow.json": [".github/workflows/*.yml", ".github/workflows/*.yaml"]
            }
      - run: |
          for f in action.yml .github/workflows/test.yml; do
            if $(jq "split(\",\") | all(. != \"$f\")" <<< '"${{ steps.validate-yaml-schema.outputs.validFiles }}"'); then
              echo "$f was not validated"
              exit 1
            fi
          done
        shell: bash
