name: Validate YAML

on:
  push:
    #paths:
      #- "*.yaml"
      #- "*.yml"
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Validate all YAML files
        run: yamllint -d relaxed .
