name: Validate YAML

on:
  push:
    paths:
      - "nspanel_blueprint.yaml"
      - "nspanel_esphome.yaml"
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Validate nspanel_blueprint.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_blueprint.yaml
      - name: Validate nspanel_esphome.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_esphome.yaml
