name: Validate YAML

on:
  push:
    #paths:
      #- "*.yaml"
      #- "*.yml"
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Validate nspanel_blueprint.yaml
        run: yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" nspanel_blueprint.yaml
      - name: Validate nspanel_esphome.yaml
        run: yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" nspanel_esphome.yaml
